// <auto-generated />
namespace PrivateClinic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Add_userid_to_Patient_object : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_userid_to_Patient_object));
        
        string IMigrationMetadata.Id
        {
            get { return "201312090134402_Add_userid_to_Patient_object"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
